"""
Django settings for shopping project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a&1j27^!giohxxnq1j%_ivw!yviyj0a2*n$k=3+8v!n-+9z$ij'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    'rest_framework',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.openid_connect',  
    # 'django.contrib.auth.backends.ModelBackend',  
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

# AUTHENTICATION_BACKENDS = [
#     'your_project.auth.MyOIDCBackend',
#     'django.contrib.auth.backends.ModelBackend',
# ]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'allauth.account.middleware.AccountMiddleware',
    # 'keycloak_oidc.middleware.OIDCMiddleware', 
]

ROOT_URLCONF = 'shopping.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.trending_products',
            ],
        },
    },
]

WSGI_APPLICATION = 'shopping.wsgi.application'
LOGOUT_REDIRECT_URL = 'http://127.0.0.1:8000/shop/home'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'shopping',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD':'12345678',
        'PORT': '3306'
    }
}

OIDC_STORE_ID_TOKEN = True # for logging out in both keycloak and website at the same time

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'

MEDIA_URL='/images/'
MEDIA_ROOT = BASE_DIR/'static'

STATICFILES_DIRS=[
    BASE_DIR/'static'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#keycloak configurations

KEYCLOAK_SERVER_URL = 'http://localhost:8080/'
KEYCLOAK_REALM = 'shopkart'
KEYCLOAK_CLIENT_ID = 'shopkart-client'
KEYCLOAK_CLIENT_SECRET_KEY = 'Syl5lYB28Sh7h6ibcny3RUudyxDVhYqy'
KEYCLOAK_ADMIN_CLIENT_ID = 'shopkart-client'
KEYCLOAK_ADMIN_CLIENT_SECRET = 'Syl5lYB28Sh7h6ibcny3RUudyxDVhYqy'


# KEYCLOAK_AUTH = {  
#     'REALM': 'shopkart',  
#     'CLIENT_ID': 'shopkart-client',  
#     'CLIENT_SECRET': 'Syl5lYB28Sh7h6ibcny3RUudyxDVhYq',  
#     'OIDC_ENDPOINT': 'http://localhost:8080/auth/realms/shopkart',  
# }